[project]
name = "homework-lesson-8"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.12"
dependencies = [
    "langchain>=1.2.0",
    "langchain-core>=1.2.0",
    "langchain-openai==1.1.11",
    "langchain-community>=0.4",
    "langchain-classic>=1.0",
    "faiss-cpu",
    "rank_bm25",
    "sentence-transformers",
    "ddgs>=7.0",
    "trafilatura>=2.0.0",
    "pypdf",
    "pydantic>=2.12.0",
    "pydantic-settings>=2.12.0",
    "langgraph>=1.0.0"
]